#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Border_Bottom_Box_Rounded

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Border-Bottom-Box-Rounded.Border-Bottom-Box-Rounded_C
// 0x0000 (0x00B8 - 0x00B8)
class UBorder_Bottom_Box_Rounded_C final : public UCommonBorderStyle
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Border-Bottom-Box-Rounded_C">();
	}
	static class UBorder_Bottom_Box_Rounded_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBorder_Bottom_Box_Rounded_C>();
	}
};
static_assert(alignof(UBorder_Bottom_Box_Rounded_C) == 0x000008, "Wrong alignment on UBorder_Bottom_Box_Rounded_C");
static_assert(sizeof(UBorder_Bottom_Box_Rounded_C) == 0x0000B8, "Wrong size on UBorder_Bottom_Box_Rounded_C");

}

