#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CompendiumUpsellPage

#include "Basic.hpp"

#include "CompendiumUpsellPage_classes.hpp"
#include "CompendiumUpsellPage_parameters.hpp"


namespace SDK
{

// Function CompendiumUpsellPage.CompendiumUpsellPage_C.ExecuteUbergraph_CompendiumUpsellPage
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCompendiumUpsellPage_C::ExecuteUbergraph_CompendiumUpsellPage(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CompendiumUpsellPage_C", "ExecuteUbergraph_CompendiumUpsellPage");

	Params::CompendiumUpsellPage_C_ExecuteUbergraph_CompendiumUpsellPage Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CompendiumUpsellPage.CompendiumUpsellPage_C.BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_56_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCompendiumUpsellPage_C::BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_56_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CompendiumUpsellPage_C", "BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_56_CommonButtonClicked__DelegateSignature");

	Params::CompendiumUpsellPage_C_BndEvt__PurchaseButton_K2Node_ComponentBoundEvent_56_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CompendiumUpsellPage.CompendiumUpsellPage_C.SetCompendium
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFortCompendiumItemDefinition*    CompendiumItemDefinition_0                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCompendiumUpsellPage_C::SetCompendium(class UFortCompendiumItemDefinition* CompendiumItemDefinition_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CompendiumUpsellPage_C", "SetCompendium");

	Params::CompendiumUpsellPage_C_SetCompendium Parms{};

	Parms.CompendiumItemDefinition_0 = CompendiumItemDefinition_0;

	UObject::ProcessEvent(Func, &Parms);
}

}

