#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CompendiumProgressWidget

#include "Basic.hpp"

#include "CompendiumProgressWidget_classes.hpp"
#include "CompendiumProgressWidget_parameters.hpp"


namespace SDK
{

// Function CompendiumProgressWidget.CompendiumProgressWidget_C.ExecuteUbergraph_CompendiumProgressWidget
// ()
// Parameters:
// int32                                   EntryPoint                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCompendiumProgressWidget_C::ExecuteUbergraph_CompendiumProgressWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CompendiumProgressWidget_C", "ExecuteUbergraph_CompendiumProgressWidget");

	Params::CompendiumProgressWidget_C_ExecuteUbergraph_CompendiumProgressWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function CompendiumProgressWidget.CompendiumProgressWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UCompendiumProgressWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CompendiumProgressWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function CompendiumProgressWidget.CompendiumProgressWidget_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// int32                                   Required                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   Achieved                                               (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UCompendiumProgressWidget_C::Update(int32 Required, int32 Achieved)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("CompendiumProgressWidget_C", "Update");

	Params::CompendiumProgressWidget_C_Update Parms{};

	Parms.Required = Required;
	Parms.Achieved = Achieved;

	UObject::ProcessEvent(Func, &Parms);
}

}

