#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HalloweenQuestsTile

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.ExecuteUbergraph_HalloweenQuestsTile
// 0x0040 (0x0040 - 0x0000)
struct HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0010)(ZeroConstructor, NoDestructor)
	int32                                         Temp_int_Variable;                                 // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Variable2;                                // 0x001C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsEventUnlocked_IsUnlocked;               // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Select_Default;                             // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile");
static_assert(sizeof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile) == 0x000040, "Wrong size on HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, EntryPoint) == 0x000000, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::EntryPoint' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, Temp_bool_Variable) == 0x000004, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, Temp_int_Variable) == 0x000018, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::Temp_int_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, Temp_int_Variable2) == 0x00001C, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::Temp_int_Variable2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, CallFunc_IsEventUnlocked_IsUnlocked) == 0x000020, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::CallFunc_IsEventUnlocked_IsUnlocked' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, CallFunc_GetContext_ReturnValue) == 0x000028, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, CallFunc_GetQuestManager_ReturnValue) == 0x000030, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile, K2Node_Select_Default) == 0x000038, "Member 'HalloweenQuestsTile_C_ExecuteUbergraph_HalloweenQuestsTile::K2Node_Select_Default' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.UpdateSideQuestInfo
// 0x0138 (0x0138 - 0x0000)
struct HalloweenQuestsTile_C_UpdateSideQuestInfo final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1C[0x4];                                       // 0x001C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue;       // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDisplayName_ReturnValue;               // 0x0030(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x3];                                       // 0x0049(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x004C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable2;                    // 0x0050(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestObjectiveInfo*                CallFunc_Array_Get_Item;                           // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0060(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisibleToUser_ReturnValue;              // 0x0064(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable2;                   // 0x0068(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Array_Index_Variable3;                    // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0070(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x0074(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0078(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x007C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue;                // 0x0080(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0081(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_82[0x2];                                       // 0x0082(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable3;                   // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue3;                  // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue3;                     // 0x008C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_8D[0x3];                                       // 0x008D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestObjectiveInfo*                CallFunc_Array_Get_Item2;                          // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue3;                // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue2;                   // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsVisibleToUser_ReturnValue2;             // 0x00A1(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A2[0x2];                                       // 0x00A2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable4;                   // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue2;                  // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue3;                 // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue2;             // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue4;                  // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C4[0x4];                                       // 0x00C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue2;      // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetDisplayName_ReturnValue2;              // 0x00D0(0x0018)()
	bool                                          CallFunc_IsValid_ReturnValue4;                     // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestObjectiveInfo*                CallFunc_Array_Get_Item3;                          // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue4;                // 0x00F8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsVisibleToUser_ReturnValue3;             // 0x00FC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue4;                 // 0x00FD(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_FE[0x2];                                       // 0x00FE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable4;                    // 0x0100(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_104[0x4];                                      // 0x0104(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItem*                         CallFunc_Array_Get_Item4;                          // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue5;                     // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue2;               // 0x0111(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0112(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0113(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0114(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0115(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_116[0x2];                                      // 0x0116(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue3;                   // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue6;                     // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue3;               // 0x011D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchEnum2_CmpSuccess;                     // 0x011E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11F[0x1];                                      // 0x011F(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetDisplayName_ReturnValue3;              // 0x0120(0x0018)()
};
static_assert(alignof(HalloweenQuestsTile_C_UpdateSideQuestInfo) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_UpdateSideQuestInfo");
static_assert(sizeof(HalloweenQuestsTile_C_UpdateSideQuestInfo) == 0x000138, "Wrong size on HalloweenQuestsTile_C_UpdateSideQuestInfo");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Array_Index_Variable) == 0x000000, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestManager_ReturnValue) == 0x000010, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Loop_Counter_Variable) == 0x000018, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestWithDefinition_ReturnValue) == 0x000020, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestWithDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Add_IntInt_ReturnValue) == 0x000028, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetDisplayName_ReturnValue) == 0x000030, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsValid_ReturnValue) == 0x000048, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Length_ReturnValue) == 0x00004C, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Array_Index_Variable2) == 0x000050, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Array_Index_Variable2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Get_Item) == 0x000058, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Add_ReturnValue) == 0x000060, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsVisibleToUser_ReturnValue) == 0x000064, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsVisibleToUser_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Loop_Counter_Variable2) == 0x000068, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Loop_Counter_Variable2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Array_Index_Variable3) == 0x00006C, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Array_Index_Variable3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Less_IntInt_ReturnValue) == 0x000070, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Add_IntInt_ReturnValue2) == 0x000074, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsValid_ReturnValue2) == 0x000078, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Length_ReturnValue2) == 0x00007C, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestState_ReturnValue) == 0x000080, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestState_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, K2Node_SwitchEnum_CmpSuccess) == 0x000081, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Loop_Counter_Variable3) == 0x000084, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Loop_Counter_Variable3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Add_IntInt_ReturnValue3) == 0x000088, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Add_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsValid_ReturnValue3) == 0x00008C, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsValid_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Get_Item2) == 0x000090, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Length_ReturnValue3) == 0x000098, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Length_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Add_ReturnValue2) == 0x00009C, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Add_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Less_IntInt_ReturnValue2) == 0x0000A0, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsVisibleToUser_ReturnValue2) == 0x0000A1, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsVisibleToUser_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Loop_Counter_Variable4) == 0x0000A4, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Loop_Counter_Variable4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetContext_ReturnValue2) == 0x0000A8, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetContext_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Less_IntInt_ReturnValue3) == 0x0000B0, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Less_IntInt_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestManager_ReturnValue2) == 0x0000B8, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestManager_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Add_IntInt_ReturnValue4) == 0x0000C0, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Add_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestWithDefinition_ReturnValue2) == 0x0000C8, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestWithDefinition_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetDisplayName_ReturnValue2) == 0x0000D0, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetDisplayName_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsValid_ReturnValue4) == 0x0000E8, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsValid_ReturnValue4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Get_Item3) == 0x0000F0, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Get_Item3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Length_ReturnValue4) == 0x0000F8, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Length_ReturnValue4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsVisibleToUser_ReturnValue3) == 0x0000FC, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsVisibleToUser_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Less_IntInt_ReturnValue4) == 0x0000FD, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Less_IntInt_ReturnValue4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_int_Array_Index_Variable4) == 0x000100, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_int_Array_Index_Variable4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Get_Item4) == 0x000108, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Get_Item4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsValid_ReturnValue5) == 0x000110, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsValid_ReturnValue5' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestState_ReturnValue2) == 0x000111, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestState_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000112, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, Temp_bool_True_if_break_was_hit_Variable) == 0x000113, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::Temp_bool_True_if_break_was_hit_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Not_PreBool_ReturnValue) == 0x000114, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Not_PreBool_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_BooleanAND_ReturnValue) == 0x000115, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_Array_Add_ReturnValue3) == 0x000118, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_Array_Add_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_IsValid_ReturnValue6) == 0x00011C, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_IsValid_ReturnValue6' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetQuestState_ReturnValue3) == 0x00011D, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetQuestState_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, K2Node_SwitchEnum2_CmpSuccess) == 0x00011E, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::K2Node_SwitchEnum2_CmpSuccess' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_UpdateSideQuestInfo, CallFunc_GetDisplayName_ReturnValue3) == 0x000120, "Member 'HalloweenQuestsTile_C_UpdateSideQuestInfo::CallFunc_GetDisplayName_ReturnValue3' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.IsEventUnlocked
// 0x0028 (0x0028 - 0x0000)
struct HalloweenQuestsTile_C_IsEventUnlocked final
{
public:
	bool                                          IsUnlocked;                                        // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue;       // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue;                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue2;         // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(HalloweenQuestsTile_C_IsEventUnlocked) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_IsEventUnlocked");
static_assert(sizeof(HalloweenQuestsTile_C_IsEventUnlocked) == 0x000028, "Wrong size on HalloweenQuestsTile_C_IsEventUnlocked");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, IsUnlocked) == 0x000000, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::IsUnlocked' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_GetQuestManager_ReturnValue) == 0x000010, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_GetQuestWithDefinition_ReturnValue) == 0x000018, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_GetQuestWithDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_GetQuestState_ReturnValue) == 0x000020, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_GetQuestState_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000021, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_EqualEqual_ByteByte_ReturnValue2) == 0x000022, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_EqualEqual_ByteByte_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_IsEventUnlocked, CallFunc_BooleanOR_ReturnValue) == 0x000023, "Member 'HalloweenQuestsTile_C_IsEventUnlocked::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.PopulateVladQuestArray
// 0x0048 (0x0048 - 0x0000)
struct HalloweenQuestsTile_C_PopulateVladQuestArray final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItemDefinition*               CallFunc_Array_Get_Item;                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue;       // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0034(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HalloweenQuestsTile_C_PopulateVladQuestArray) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_PopulateVladQuestArray");
static_assert(sizeof(HalloweenQuestsTile_C_PopulateVladQuestArray) == 0x000048, "Wrong size on HalloweenQuestsTile_C_PopulateVladQuestArray");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, Temp_int_Array_Index_Variable) == 0x000000, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_Array_Get_Item) == 0x000008, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_GetContext_ReturnValue) == 0x000018, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_GetQuestManager_ReturnValue) == 0x000020, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_GetQuestWithDefinition_ReturnValue) == 0x000028, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_GetQuestWithDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_IsValid_ReturnValue) == 0x000030, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_Array_Add_ReturnValue) == 0x000034, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, Temp_int_Loop_Counter_Variable) == 0x000038, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_Less_IntInt_ReturnValue) == 0x00003C, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateVladQuestArray, CallFunc_Add_IntInt_ReturnValue) == 0x000040, "Member 'HalloweenQuestsTile_C_PopulateVladQuestArray::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.Configure Rewards and Timers
// 0x0058 (0x0058 - 0x0000)
struct HalloweenQuestsTile_C_Configure_Rewards_and_Timers final
{
public:
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue;       // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue2;                  // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue2;             // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue2;      // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue;                // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue2;                     // 0x0039(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x003A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue2;         // 0x003B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue2;               // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue3;         // 0x003E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue4;         // 0x003F(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue2;                   // 0x0040(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue3;                     // 0x0041(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	EFortQuestState                               CallFunc_GetQuestState_ReturnValue3;               // 0x0042(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue5;         // 0x0043(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue6;         // 0x0044(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_BooleanOR_ReturnValue3;                   // 0x0045(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_46[0x2];                                       // 0x0046(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x0048(0x0008)(NoDestructor)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue2;                 // 0x0050(0x0008)(NoDestructor)
};
static_assert(alignof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_Configure_Rewards_and_Timers");
static_assert(sizeof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers) == 0x000058, "Wrong size on HalloweenQuestsTile_C_Configure_Rewards_and_Timers");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetContext_ReturnValue) == 0x000000, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestManager_ReturnValue) == 0x000008, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestWithDefinition_ReturnValue) == 0x000010, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestWithDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetContext_ReturnValue2) == 0x000018, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetContext_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_IsValid_ReturnValue) == 0x000020, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestManager_ReturnValue2) == 0x000028, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestManager_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestWithDefinition_ReturnValue2) == 0x000030, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestWithDefinition_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestState_ReturnValue) == 0x000038, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestState_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_IsValid_ReturnValue2) == 0x000039, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_IsValid_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x00003A, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_EqualEqual_ByteByte_ReturnValue2) == 0x00003B, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_EqualEqual_ByteByte_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestState_ReturnValue2) == 0x00003C, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestState_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_BooleanOR_ReturnValue) == 0x00003D, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_BooleanOR_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_EqualEqual_ByteByte_ReturnValue3) == 0x00003E, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_EqualEqual_ByteByte_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_EqualEqual_ByteByte_ReturnValue4) == 0x00003F, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_EqualEqual_ByteByte_ReturnValue4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_BooleanOR_ReturnValue2) == 0x000040, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_BooleanOR_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_IsValid_ReturnValue3) == 0x000041, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_IsValid_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_GetQuestState_ReturnValue3) == 0x000042, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_GetQuestState_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_EqualEqual_ByteByte_ReturnValue5) == 0x000043, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_EqualEqual_ByteByte_ReturnValue5' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_EqualEqual_ByteByte_ReturnValue6) == 0x000044, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_EqualEqual_ByteByte_ReturnValue6' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_BooleanOR_ReturnValue3) == 0x000045, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_BooleanOR_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_K2_SetTimer_ReturnValue) == 0x000048, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_K2_SetTimer_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_Configure_Rewards_and_Timers, CallFunc_K2_SetTimer_ReturnValue2) == 0x000050, "Member 'HalloweenQuestsTile_C_Configure_Rewards_and_Timers::CallFunc_K2_SetTimer_ReturnValue2' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.SetupSideQuestRewards
// 0x0040 (0x0040 - 0x0000)
struct HalloweenQuestsTile_C_SetupSideQuestRewards final
{
public:
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue; // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue2; // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue3; // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue4; // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue5; // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue6; // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue7; // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortItem*                              CallFunc_CreateTemporaryItemInstanceBP_ReturnValue8; // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HalloweenQuestsTile_C_SetupSideQuestRewards) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_SetupSideQuestRewards");
static_assert(sizeof(HalloweenQuestsTile_C_SetupSideQuestRewards) == 0x000040, "Wrong size on HalloweenQuestsTile_C_SetupSideQuestRewards");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue) == 0x000000, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue2) == 0x000008, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue3) == 0x000010, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue4) == 0x000018, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue5) == 0x000020, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue5' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue6) == 0x000028, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue6' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue7) == 0x000030, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue7' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetupSideQuestRewards, CallFunc_CreateTemporaryItemInstanceBP_ReturnValue8) == 0x000038, "Member 'HalloweenQuestsTile_C_SetupSideQuestRewards::CallFunc_CreateTemporaryItemInstanceBP_ReturnValue8' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.SetQuestPlayButton
// 0x0100 (0x0100 - 0x0000)
struct HalloweenQuestsTile_C_SetQuestPlayButton final
{
public:
	class UFortQuestItem*                         Quest_Item;                                        // 0x0000(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanPlayQuest;                                      // 0x0008(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable;                     // 0x000C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            CallFunc_GetItemSmallPreviewImageBrush_ReturnValue; // 0x0010(0x0090)()
	class FText                                   CallFunc_GetDisplayName_ReturnValue;               // 0x00A0(0x0018)()
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00B8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00C0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C1[0x3];                                       // 0x00C1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TrySetQuestButton_CanPlayQuest;           // 0x00C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_TrySetQuestButton_CanPlayQuest2;          // 0x00C9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_CA[0x2];                                       // 0x00CA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Loop_Counter_Variable2;                   // 0x00CC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Add_IntInt_ReturnValue2;                  // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TrySetQuestButton_CanPlayQuest3;          // 0x00D4(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_D5[0x3];                                       // 0x00D5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         Temp_int_Array_Index_Variable2;                    // 0x00D8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC[0x4];                                       // 0x00DC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItem*                         CallFunc_Array_Get_Item;                           // 0x00E0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_TrySetQuestButton_CanPlayQuest4;          // 0x00E8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Array_Length_ReturnValue2;                // 0x00EC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestItem*                         CallFunc_Array_Get_Item2;                          // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Less_IntInt_ReturnValue2;                 // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_TrySetQuestButton_CanPlayQuest5;          // 0x00F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(HalloweenQuestsTile_C_SetQuestPlayButton) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_SetQuestPlayButton");
static_assert(sizeof(HalloweenQuestsTile_C_SetQuestPlayButton) == 0x000100, "Wrong size on HalloweenQuestsTile_C_SetQuestPlayButton");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, Quest_Item) == 0x000000, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::Quest_Item' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CanPlayQuest) == 0x000008, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CanPlayQuest' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, Temp_int_Array_Index_Variable) == 0x00000C, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_GetItemSmallPreviewImageBrush_ReturnValue) == 0x000010, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_GetItemSmallPreviewImageBrush_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_GetDisplayName_ReturnValue) == 0x0000A0, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_GetDisplayName_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Array_Length_ReturnValue) == 0x0000B8, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, Temp_int_Loop_Counter_Variable) == 0x0000BC, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Less_IntInt_ReturnValue) == 0x0000C0, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Add_IntInt_ReturnValue) == 0x0000C4, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_TrySetQuestButton_CanPlayQuest) == 0x0000C8, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_TrySetQuestButton_CanPlayQuest' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_TrySetQuestButton_CanPlayQuest2) == 0x0000C9, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_TrySetQuestButton_CanPlayQuest2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, Temp_int_Loop_Counter_Variable2) == 0x0000CC, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::Temp_int_Loop_Counter_Variable2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Add_IntInt_ReturnValue2) == 0x0000D0, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Add_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_TrySetQuestButton_CanPlayQuest3) == 0x0000D4, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_TrySetQuestButton_CanPlayQuest3' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, Temp_int_Array_Index_Variable2) == 0x0000D8, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::Temp_int_Array_Index_Variable2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Array_Get_Item) == 0x0000E0, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_TrySetQuestButton_CanPlayQuest4) == 0x0000E8, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_TrySetQuestButton_CanPlayQuest4' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Array_Length_ReturnValue2) == 0x0000EC, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Array_Length_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Array_Get_Item2) == 0x0000F0, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Array_Get_Item2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_Less_IntInt_ReturnValue2) == 0x0000F8, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_Less_IntInt_ReturnValue2' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_SetQuestPlayButton, CallFunc_TrySetQuestButton_CanPlayQuest5) == 0x0000F9, "Member 'HalloweenQuestsTile_C_SetQuestPlayButton::CallFunc_TrySetQuestButton_CanPlayQuest5' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.TrySetQuestButton
// 0x0010 (0x0010 - 0x0000)
struct HalloweenQuestsTile_C_TrySetQuestButton final
{
public:
	class UFortQuestItem*                         Quest;                                             // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CanPlayQuest;                                      // 0x0008(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_HasCompletedQuest_ReturnValue;            // 0x0009(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_GetIsEnabled_ReturnValue;                 // 0x000A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x000B(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(HalloweenQuestsTile_C_TrySetQuestButton) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_TrySetQuestButton");
static_assert(sizeof(HalloweenQuestsTile_C_TrySetQuestButton) == 0x000010, "Wrong size on HalloweenQuestsTile_C_TrySetQuestButton");
static_assert(offsetof(HalloweenQuestsTile_C_TrySetQuestButton, Quest) == 0x000000, "Member 'HalloweenQuestsTile_C_TrySetQuestButton::Quest' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_TrySetQuestButton, CanPlayQuest) == 0x000008, "Member 'HalloweenQuestsTile_C_TrySetQuestButton::CanPlayQuest' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_TrySetQuestButton, CallFunc_HasCompletedQuest_ReturnValue) == 0x000009, "Member 'HalloweenQuestsTile_C_TrySetQuestButton::CallFunc_HasCompletedQuest_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_TrySetQuestButton, CallFunc_GetIsEnabled_ReturnValue) == 0x00000A, "Member 'HalloweenQuestsTile_C_TrySetQuestButton::CallFunc_GetIsEnabled_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_TrySetQuestButton, CallFunc_IsValid_ReturnValue) == 0x00000B, "Member 'HalloweenQuestsTile_C_TrySetQuestButton::CallFunc_IsValid_ReturnValue' has a wrong offset!");

// Function HalloweenQuestsTile.HalloweenQuestsTile_C.PopulateMainQuestArray
// 0x0048 (0x0048 - 0x0000)
struct HalloweenQuestsTile_C_PopulateMainQuestArray final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItemDefinition*               CallFunc_Array_Get_Item;                           // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortQuestManager*                      CallFunc_GetQuestManager_ReturnValue;              // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortQuestItem*                         CallFunc_GetQuestWithDefinition_ReturnValue;       // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0038(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x003C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x003D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_3E[0x2];                                       // 0x003E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(HalloweenQuestsTile_C_PopulateMainQuestArray) == 0x000008, "Wrong alignment on HalloweenQuestsTile_C_PopulateMainQuestArray");
static_assert(sizeof(HalloweenQuestsTile_C_PopulateMainQuestArray) == 0x000048, "Wrong size on HalloweenQuestsTile_C_PopulateMainQuestArray");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, Temp_int_Array_Index_Variable) == 0x000000, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::Temp_int_Array_Index_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_Array_Get_Item) == 0x000008, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_Array_Length_ReturnValue) == 0x000010, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_GetContext_ReturnValue) == 0x000018, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_GetQuestManager_ReturnValue) == 0x000020, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_GetQuestManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, Temp_int_Loop_Counter_Variable) == 0x000028, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::Temp_int_Loop_Counter_Variable' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_GetQuestWithDefinition_ReturnValue) == 0x000030, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_GetQuestWithDefinition_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_Array_Add_ReturnValue) == 0x000038, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_Array_Add_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_IsValid_ReturnValue) == 0x00003C, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_Less_IntInt_ReturnValue) == 0x00003D, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(HalloweenQuestsTile_C_PopulateMainQuestArray, CallFunc_Add_IntInt_ReturnValue) == 0x000040, "Member 'HalloweenQuestsTile_C_PopulateMainQuestArray::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

}

