#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LaunchPad_Transition

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum LaunchPad_Transition.LaunchPad_Transition
// NumValues: 0x0004
enum class ELaunchPad_Transition : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	LaunchPad_MAX                            = 3,
};

}

