#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_Base_S_Blue_0

#include "Basic.hpp"

#include "TextStyle_Base_S_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-Base-S_Blue.TextStyle-Base-S_Blue_C
// 0x0000 (0x00D0 - 0x00D0)
class TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C final : public UTextStyle_Base_S_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BlueprintGeneratedClass TextStyle-Base-S_Blue.TextStyle-Base-S_Blue_C", true, "TextStyle-Base-S_Blue_C">();
	}
	static class TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C>();
	}
};
static_assert(alignof(TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C) == 0x000008, "Wrong alignment on TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C");
static_assert(sizeof(TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C) == 0x0000D0, "Wrong size on TextStyle_Base_S_Blue_0::UTextStyle_Base_S_Blue_C");

}

